### PR TITLE
Add support for PATCH.

### PR DESCRIPTION
**Pull request by ctriv**
Pretty strait-forward, just adding PATCH.

### CODE REVIEW

**Comment by theory** [comment]
Docs?

**Comment by ctriv** [comment]
There isn't much in the way in the docs right now for things like PATCH or TRACE, just a list of supported http methods (which I added PATCH to).  What sort of docs are you looking for?

**Comment by theory** [comment]
Oh, that'l do, missed that line when I scanned the patch. Thanks!

**Comment by theory** [comment]
v0.21 on its way to CPAN with this change. Thank you!

**Comment by ctriv** [comment]
Awesome! Thank you very much. 

-- 
Chris Reinhardt

**Pull request merged**
